### ISSUE TITLE
support all LLVM languages

### ISSUE THREAD

**Issue by AchalaSB** [bluele/hypermint#3]
@bluele I wanted to know how hypermint support other languages?
What is the roadmap for same?
Can I get pipeline for smart contract?

And now its supporting `Rust` , Is there any limitations that hypermint facing?

**Comment by bluele** [comment]
@AchalaSB 
hypermint has supports for standalone WebAssembly file which is generated by rust-wasm and [dcodeID/webassembly](https://github.com/dcodeIO/webassembly) etc, but don't have supports for a file which requires a runtime like emscripten.
If you are interested with other language support(c, c++), it might be a good idea to use dcodeID/webassembly.
